// Code generated by rescodegen. DO NOT EDIT.

package serve

import (
	"github.com/restayway/rescode"
	"google.golang.org/grpc/codes"
)

// Error code constants
const (
	GeneralErrorCode uint64     = 1
	GeneralErrorHTTP int        = 501
	GeneralErrorGRPC codes.Code = 0
	GeneralErrorMsg  string     = "General Error"

	InvalidSignaturesCode uint64     = 2
	InvalidSignaturesHTTP int        = 404
	InvalidSignaturesGRPC codes.Code = 0
	InvalidSignaturesMsg  string     = "Invalid Signatures"
)

// GeneralError creates a new GeneralError error.
func GeneralError(err ...error) *rescode.RC {
	return rescode.New(GeneralErrorCode, GeneralErrorHTTP, GeneralErrorGRPC, GeneralErrorMsg)(err...)
}

// InvalidSignatures creates a new InvalidSignatures error.
func InvalidSignatures(err ...error) *rescode.RC {
	return rescode.New(InvalidSignaturesCode, InvalidSignaturesHTTP, InvalidSignaturesGRPC, InvalidSignaturesMsg)(err...)
}
