// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"github.com/labstack/echo/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostAuthKerberos Authenticate to the server using a local kerberos ticket
	// (POST /auth/kerberos)
	PostAuthKerberos(ctx *echo.Context) error
	// PostAuthPassword Authenticate to the server with a username and password
	// (POST /auth/password)
	PostAuthPassword(ctx *echo.Context) error
	// GetKeysAvailable List the currently available keys to the server
	// (GET /keys/available)
	GetKeysAvailable(ctx *echo.Context) error
	// PostKeysAvailable Add a new public or private key to the server
	// (POST /keys/available)
	PostKeysAvailable(ctx *echo.Context) error
	// PostKeysGenerate Generate a new private key on the server and return the public key
	// (POST /keys/generate)
	PostKeysGenerate(ctx *echo.Context) error
	// GetPing Status check for server availability
	// (GET /ping)
	GetPing(ctx *echo.Context) error
	// GetServeResigning Return the current resigning configuration
	// (GET /serve/resigning)
	GetServeResigning(ctx *echo.Context) error
	// PostServeResigning Add a new resigning configuration
	// (POST /serve/resigning)
	PostServeResigning(ctx *echo.Context) error
	// GetUploadAcceptedKeys List the current signing keys accepted for uploads.
	// (GET /upload/accepted-keys)
	GetUploadAcceptedKeys(ctx *echo.Context) error
	// PostUploadAcceptedKeys Add a new signing key which will be accepted for uploads
	// (POST /upload/accepted-keys)
	PostUploadAcceptedKeys(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAuthKerberos converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthKerberos(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthKerberos(ctx)
	return err
}

// PostAuthPassword converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthPassword(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthPassword(ctx)
	return err
}

// GetKeysAvailable converts echo context to params.
func (w *ServerInterfaceWrapper) GetKeysAvailable(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetKeysAvailable(ctx)
	return err
}

// PostKeysAvailable converts echo context to params.
func (w *ServerInterfaceWrapper) PostKeysAvailable(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostKeysAvailable(ctx)
	return err
}

// PostKeysGenerate converts echo context to params.
func (w *ServerInterfaceWrapper) PostKeysGenerate(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostKeysGenerate(ctx)
	return err
}

// GetPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetPing(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPing(ctx)
	return err
}

// GetServeResigning converts echo context to params.
func (w *ServerInterfaceWrapper) GetServeResigning(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServeResigning(ctx)
	return err
}

// PostServeResigning converts echo context to params.
func (w *ServerInterfaceWrapper) PostServeResigning(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostServeResigning(ctx)
	return err
}

// GetUploadAcceptedKeys converts echo context to params.
func (w *ServerInterfaceWrapper) GetUploadAcceptedKeys(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUploadAcceptedKeys(ctx)
	return err
}

// PostUploadAcceptedKeys converts echo context to params.
func (w *ServerInterfaceWrapper) PostUploadAcceptedKeys(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUploadAcceptedKeys(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/ping", wrapper.GetPing, options.OperationMiddlewares["GetPing"]...)
	router.POST(options.BaseURL+"/auth/password", wrapper.PostAuthPassword, options.OperationMiddlewares["PostAuthPassword"]...)
	router.POST(options.BaseURL+"/auth/kerberos", wrapper.PostAuthKerberos, options.OperationMiddlewares["PostAuthKerberos"]...)
	router.GET(options.BaseURL+"/keys/available", wrapper.GetKeysAvailable, options.OperationMiddlewares["GetKeysAvailable"]...)
	router.POST(options.BaseURL+"/keys/available", wrapper.PostKeysAvailable, options.OperationMiddlewares["PostKeysAvailable"]...)
	router.POST(options.BaseURL+"/keys/generate", wrapper.PostKeysGenerate, options.OperationMiddlewares["PostKeysGenerate"]...)
	router.GET(options.BaseURL+"/upload/accepted-keys", wrapper.GetUploadAcceptedKeys, options.OperationMiddlewares["GetUploadAcceptedKeys"]...)
	router.POST(options.BaseURL+"/upload/accepted-keys", wrapper.PostUploadAcceptedKeys, options.OperationMiddlewares["PostUploadAcceptedKeys"]...)
	router.GET(options.BaseURL+"/serve/resigning", wrapper.GetServeResigning, options.OperationMiddlewares["GetServeResigning"]...)
	router.POST(options.BaseURL+"/serve/resigning", wrapper.PostServeResigning, options.OperationMiddlewares["PostServeResigning"]...)

}
