// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package nixstore

import (
	"fmt"
	"strings"
)

const (
	// NarURLFormatConventionAuto is a NarURLFormatConvention of type auto.
	// Autodetect filehash suitability and fallback to nixhash otherwise
	NarURLFormatConventionAuto NarURLFormatConvention = "auto"
	// NarURLFormatConventionNixhash is a NarURLFormatConvention of type nixhash.
	// Use the Nix hash path for lookups
	NarURLFormatConventionNixhash NarURLFormatConvention = "nixhash"
	// NarURLFormatConventionFilehash is a NarURLFormatConvention of type filehash.
	// Use the filehash only. Slow if an index on the hash is not included
	NarURLFormatConventionFilehash NarURLFormatConvention = "filehash"
)

var ErrInvalidNarURLFormatConvention = fmt.Errorf("not a valid NarURLFormatConvention, try [%s]", strings.Join(_NarURLFormatConventionNames, ", "))

var _NarURLFormatConventionNames = []string{
	string(NarURLFormatConventionAuto),
	string(NarURLFormatConventionNixhash),
	string(NarURLFormatConventionFilehash),
}

// NarURLFormatConventionNames returns a list of possible string values of NarURLFormatConvention.
func NarURLFormatConventionNames() []string {
	tmp := make([]string, len(_NarURLFormatConventionNames))
	copy(tmp, _NarURLFormatConventionNames)
	return tmp
}

// NarURLFormatConventionValues returns a list of the values for NarURLFormatConvention
func NarURLFormatConventionValues() []NarURLFormatConvention {
	return []NarURLFormatConvention{
		NarURLFormatConventionAuto,
		NarURLFormatConventionNixhash,
		NarURLFormatConventionFilehash,
	}
}

// String implements the Stringer interface.
func (x NarURLFormatConvention) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x NarURLFormatConvention) IsValid() bool {
	_, err := ParseNarURLFormatConvention(string(x))
	return err == nil
}

var _NarURLFormatConventionValue = map[string]NarURLFormatConvention{
	"auto":     NarURLFormatConventionAuto,
	"nixhash":  NarURLFormatConventionNixhash,
	"filehash": NarURLFormatConventionFilehash,
}

// ParseNarURLFormatConvention attempts to convert a string to a NarURLFormatConvention.
func ParseNarURLFormatConvention(name string) (NarURLFormatConvention, error) {
	if x, ok := _NarURLFormatConventionValue[name]; ok {
		return x, nil
	}
	return NarURLFormatConvention(""), fmt.Errorf("%s is %w", name, ErrInvalidNarURLFormatConvention)
}

// MarshalText implements the text marshaller method.
func (x NarURLFormatConvention) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *NarURLFormatConvention) UnmarshalText(text []byte) error {
	tmp, err := ParseNarURLFormatConvention(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
